verbatim:
  cabal-version: 3.4

name: diaryviewer-backend
version: 0.0.0

dependencies:
  - base >= 4.9 && < 5
  - aeson
  - directory
  - filepath
  - fsnotify
  - text
  - servant-server
  - time
  - warp

library:
  source-dirs: src
  ghc-options:
    -Wall
    -threaded
    -rtsopts
    -with-rtsopts=-N
